export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT';
export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
export const DECREASE_BUNS = 'DECREASE_BUNS';
export const CLEAR_COUNTERS = 'CLEAR_COUNTERS';